'use strict';
const expertiseChoices=['Python','Data Analysis','AI and Machine Learning','Design','Project Management','Domain Knowledge','Communication'];
const loginPrompt=()=>`<div class="wrap section">${link('/account?returnTo='+encodeURIComponent(location.hash.slice(1)),'Sign In to Participate','button')}</div>`;
const exampleTag=flag=>flag?'<span class="example-badge">Example</span>':'';
const dateOnly=value=>new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
const challengeState=c=>new Date(c.submission_deadline)>new Date()?'Open for Entries':new Date(c.voting_deadline)>new Date()?'Voting Open':'Completed';
let engagementSequence=0;
function miniCard(r){return `<article class="card recommendation">${exampleTag(r.example)}<span class="tag">${esc(r.kind==='opportunities'?'Opportunity':r.kind==='projects'?'Project':'Community')}</span><h3>${link('/'+r.kind+'/'+r.id,esc(r.title),'')}</h3><p>${esc(r.summary||'')}</p>${r.reasons?.length?`<p class="recommendation-reason">${esc(r.reasons.join(' · '))}</p>`:''}${link('/'+r.kind+'/'+r.id,'View Details →','card-bottom')}</article>`;}
function challengeCard(c){return `<article class="card challenge-card"><div class="card-top">${exampleTag(c.is_example)}<span class="tag">${challengeState(c)}</span></div><h3>${link('/build-challenges/'+c.id,esc(c.title),'')}</h3><p>${esc(c.summary)}</p><div class="challenge-facts"><span>Entries close <strong>${dateOnly(c.submission_deadline)}</strong></span><span><strong>${c.entries}</strong> entries</span></div>${link('/build-challenges/'+c.id,'View Challenge →','card-bottom')}</article>`;}
async function engagementHome(){
 if(!currentUser)return heading('Recommendations','Recommended for You')+loginPrompt();
 const data=await api('/recommendations');return heading('Recommendations','Recommended for You')+`<section class="wrap engagement-home"><div class="workspace-toolbar">${link('/profile','Edit My Profile','button outline')}${link('/opportunities','All Opportunities →')}</div>${data.items.length?`<div class="grid two">${data.items.map(miniCard).join('')}</div>`:`<div class="empty"><h3>${data.profile.categories.length||data.profile.interests?'No Matches Yet':'Set Your Interests'}</h3><p>Choose categories and skills in your profile to find relevant listings.</p>${link('/profile','Edit Profile','button outline')}</div>`}<p class="meta recommendation-note">Recommendations use your profile${data.profile.use_history?' and up to 30 days of marketplace browsing':''}.</p></section>`;
}

function formField(name,label,value='',type='text',max=3000){return `<div class="field"><label for="e-${name}">${label}</label>${type==='textarea'?`<textarea id="e-${name}" name="${name}" maxlength="${max}" required>${esc(value)}</textarea>`:`<input id="e-${name}" name="${name}" type="${type}" maxlength="${max}" value="${esc(value)}" ${name==='demo_url'?'':'required'}>`}</div>`;}
async function challengesPage(){const data=await api('/build-challenges');return heading('Opportunities','Build Challenges','Time-bound briefs with entry galleries and community voting.','/opportunities')+`<section class="wrap engagement-page">${currentUser?.isAdmin?`<div class="workspace-toolbar">${link('/build-challenges/new','Create a Build Challenge','button')}</div>`:''}<div class="grid two">${data.items.map(challengeCard).join('')}</div></section>`;}
function challengeForm(){return heading('Build Challenges','Create a Build Challenge','Published challenges appear immediately.')+(currentUser?.isAdmin?`<form id="challenge-form" class="form-wrap"><div id="engagement-message"></div>${formField('title','Title','','text',160)}${formField('summary','Summary','','textarea',500)}${formField('brief','Challenge Brief','','textarea',6000)}${formField('criteria','Submission Requirements','','textarea')}${formField('submission_deadline','Entry Deadline','','datetime-local')}${formField('voting_deadline','Voting Deadline','','datetime-local')}<p class="meta">Times use your device’s local time zone. Entries are ranked by community votes.</p><button class="button">Publish Challenge</button></form>`:loginPrompt());}
async function challengeDetail(id){
 const c=await api('/build-challenges/'+encodeURIComponent(id)),open=new Date(c.submission_deadline)>new Date(),entry=c.ownEntry;let rank=0,prev=-1;
 return heading('Build Challenges',esc(c.title),exampleTag(c.is_example)+esc(c.summary),'/build-challenges')+`<div class="wrap detail-layout"><div class="detail-body">${section('Challenge Brief',`<p class="preserve">${esc(c.brief)}</p>`)}${section('Submission Requirements',`<p class="preserve">${esc(c.criteria)}</p>`)}${section('Community-Choice Leaderboard',`<p>Ranked by votes from signed-in members.</p><div class="leaderboard">${c.entries.length?c.entries.map((e,i)=>{if(e.likes!==prev)rank=i+1;prev=e.likes;return `<a class="leaderboard-row" href="#/entries/${e.id}"><span class="rank">${e.likes?rank:'—'}</span><div><h3>${esc(e.title)}</h3><p>${esc(e.team)}</p></div><span class="ranking-score">${e.likes}<small>votes</small></span></a>`;}).join(''):'<div class="empty"><h3>No Entries Yet</h3><p>Submitted entries will appear here.</p></div>'}</div>`)}${currentUser&&open?`<section id="submit-entry"><h2>${entry?.status==='published'?'Edit Your Entry':'Submit an Entry'}</h2><p>One entry per account per challenge. Your entry appears in the public gallery.</p><form id="entry-form" data-challenge="${c.id}" data-entry="${entry?.id||newRequestId()}"><div id="engagement-message"></div>${formField('title','Entry Title',entry?.title||'','text',160)}${formField('team','Team or Participant Name',entry?.team||currentUser.name,'text',200)}${formField('summary','What You Built',entry?.summary||'','textarea')}${formField('demo_url','Demo or Repository Link (Optional)',entry?.demo_url||'','url',1500)}<button class="button">${entry?.status==='published'?'Save Entry':'Publish Entry'}</button></form></section>`:''}</div><aside class="aside"><span class="tag">${challengeState(c)}</span><dl><dt>Entry Deadline</dt><dd>${esc(stamp(c.submission_deadline))}</dd><dt>Voting Deadline</dt><dd>${esc(stamp(c.voting_deadline))}</dd><dt>Entries</dt><dd>${c.entries.length}</dd></dl>${open?(currentUser?'<a class="button" href="#submit-entry" data-jump-entry>Submit or Edit Entry</a>':link('/account?returnTo='+encodeURIComponent('/build-challenges/'+id),'Sign In to Submit','button')):''}${entry?.status==='published'?link('/entries/'+entry.id,'View Your Entry','button outline'):''}</aside></div>`;
}
async function entryDetail(id){const e=await api('/challenge-entries/'+encodeURIComponent(id));return heading('Challenge Entry',esc(e.title),esc(e.team),'/build-challenges/'+e.challenge_id)+`<div class="wrap detail-layout"><div class="detail-body">${section('Entry Overview',`<p class="preserve">${esc(e.summary)}</p>${e.demo_url?`<a href="${esc(e.demo_url)}" target="_blank" rel="noopener noreferrer" class="button outline">Open Demo or Repository ↗</a>`:''}`)}<div id="social-panel" data-kind="entries" data-record="${e.id}" data-voting-closed="${new Date(e.voting_deadline)<=new Date()}"></div></div><aside class="aside"><h3>${esc(e.challenge_title)}</h3><p>Submitted by ${esc(e.owner_name)}</p>${link('/build-challenges/'+e.challenge_id,'View Challenge','button outline')}${currentUser?.id===e.owner_id||currentUser?.isAdmin?`<div id="engagement-message"></div><button class="button outline" data-withdraw-entry="${e.id}" data-challenge="${e.challenge_id}">Withdraw Entry</button>`:''}</aside></div>`;}
async function profilePage(){
 if(!currentUser)return heading('Profile','My Profile')+loginPrompt();const p=await api('/profile');
 const choices=(name,label,values,selected)=>`<fieldset class="field skill-picker"><legend>${label}</legend><div class="skill-options">${values.map((v,i)=>`<label class="skill-option"><input type="checkbox" name="${name}" value="${esc(v)}" ${selected.includes(v)?'checked':''}><span>${esc(v)}</span></label>`).join('')}</div></fieldset>`;
 return heading('My Marketplace','My Profile','Choose what you want to explore and what you can contribute.')+`<form class="form-wrap" id="profile-form"><div id="engagement-message"></div><div class="profile-photo-editor"><div id="profile-photo-preview">${avatar(currentUser.name,p.photo,'large')}</div><div><label for="profile-photo-input" class="button outline">Choose Photo</label><input type="file" id="profile-photo-input" accept="image/jpeg,image/png,image/webp" class="sr-only"><button type="button" id="remove-profile-photo" class="text-link">Remove Photo</button><small>JPEG, PNG or WebP. Your photo uses the same visibility settings as your profile.</small><div id="photo-message" role="status"></div></div></div>${formField('affiliation','Role and Affiliation',p.affiliation,'text',200)}${choices('categories','Areas of Interest',collaborationCategories,p.categories)}${choices('skills','Skills and Experience',expertiseChoices,p.skills)}${formField('interests','Topics or Goals',p.interests,'textarea',1000)}${formField('availability','Availability',p.availability,'text',200)}<div class="profile-settings"><label class="check-row"><input type="checkbox" name="discoverable" ${p.discoverable?'checked':''}><span><strong>Make My Profile Discoverable</strong><small>Other signed-in members can find your profile. Listing owners can receive collaborator recommendations based on your interests and skills.</small></span></label><label class="check-row"><input type="checkbox" name="use_history" ${p.use_history?'checked':''}><span><strong>Use My Browsing for Recommendations</strong><small>Use listings you view on this site for up to 30 days. Turning this off clears your browsing history.</small></span></label><p class="meta">Appearing as an interested collaborator is a separate choice on each listing.</p><button type="button" class="text-link" id="hide-participation">Hide Me on All Listings</button><br><button type="button" class="text-link" id="clear-browsing">Clear Browsing History</button></div><button class="button" type="submit">Save Profile</button></form>`;
}
async function peoplePage(params){if(!currentUser)return heading('People','Find People')+loginPrompt();const q=params.get('q')||'',data=await api('/people?q='+encodeURIComponent(q));return heading('People','Find People','Members who have made their profiles discoverable.')+`<section class="wrap engagement-page"><form id="people-search" class="people-search"><label for="people-q" class="sr-only">Search interests or skills</label><input id="people-q" name="q" value="${esc(q)}" placeholder="Search interests or skills"><button class="button">Search</button>${link('/profile','Edit My Profile','button outline')}</form><div class="grid two">${data.items.length?data.items.map(p=>`<article class="card">${avatar(p.name,p.photo)}<span class="tag">Member</span><h3><a href="${esc(p.url)}">${esc(p.name)}</a></h3><p>${esc(p.affiliation)}</p>${chips(p.skills)}<p>${esc(p.interests)}</p><p class="meta">${esc(p.availability)}</p><a class="card-bottom" href="${esc(p.url)}">View Profile →</a></article>`).join(''):'<div class="empty"><h3>No Matching Profiles Yet</h3><p>Members appear here when they make their profile discoverable.</p></div>'}</div></section>`;}
async function personPage(id){if(!currentUser)return heading('People','Member Profile')+loginPrompt();const p=await api('/people/'+encodeURIComponent(id));return heading('People',esc(p.name),esc(p.affiliation),'/people')+`<section class="wrap engagement-page"><div class="profile-detail">${avatar(p.name,p.photo,'large')}${section('Interests',`<p>${esc(p.interests)}</p>`)}${section('Skills and Experience',chips(p.skills))}${section('Availability',`<p>${esc(p.availability)||'Not specified'}</p>`)}${section('Published Listings',p.listings.length?p.listings.map(r=>link('/'+r.kind+'/'+r.id,esc(r.title),'choice')).join(''):'<p>No published listings.</p>')}<button class="button outline" data-introduction="${esc(p.name)}">Request an Introduction</button></div></section>`;}

async function mountDiscussion(panel){
 const {kind,record}=panel.dataset,endpoint='/engagement/'+kind+'/'+encodeURIComponent(record);let loaded=[],lastData;
 const visible=()=>panel.isConnected;
 const replyForm=parent=>`<form class="public-comment-form" data-parent="${parent||''}"><label for="comment-${parent||'new'}">${parent?'Your Reply':'Add a Comment'}</label><textarea id="comment-${parent||'new'}" name="body" maxlength="2000" required rows="3"></textarea><button class="button outline">${parent?'Post Reply':'Post Comment'}</button><div class="comment-message"></div></form>`;
 const comment=c=>`<article class="public-comment ${c.parent_id?'reply':''}" id="comment-${c.id}-item"><div class="comment-byline"><strong>${c.deleted?'Deleted Comment':esc(c.author_name)}</strong>${c.isExample?'<span class="example-badge">Example</span>':''}<time>${esc(stamp(c.created_at))}</time></div><p class="preserve">${c.deleted?'This comment was removed.':esc(c.body)}</p><div class="comment-actions">${currentUser&&!c.deleted?`<button data-comment-like="${c.id}" class="comment-like ${c.liked?'liked':''}" aria-pressed="${Boolean(c.liked)}">${c.liked?'♥':'♡'} ${c.likes||0}</button><button data-reply="${c.id}" aria-expanded="false">Reply</button>`:''}${!currentUser&&!c.deleted?`<span class="comment-like-count">♡ ${c.likes||0}</span>`:''}${c.canDelete?`<button data-delete-comment="${c.id}">Delete</button>`:''}</div><div class="reply-slot" data-reply-slot="${c.id}"></div></article>`;
 const tree=(parent=null,depth=0)=>loaded.filter(c=>(c.parent_id||null)===parent).map(c=>`${comment(c)}${depth<12?`<div class="comment-replies">${tree(c.id,depth+1)}</div>`:''}`).join('');
 async function load(reset=true,preserveDrafts=false){
  const savedDrafts=preserveDrafts?[...panel.querySelectorAll('.public-comment-form')].map(form=>({parent:form.dataset.parent,body:form.elements.body.value})):[];
  const data=await api(endpoint+'?offset='+(reset?0:loaded.length));if(!visible())return;lastData=data;loaded=reset?data.comments:[...loaded,...data.comments];
  const votingClosed=kind==='entries'&&panel.dataset.votingClosed==='true';
  panel.innerHTML=`<section class="discussion"><div class="social-toolbar"><button class="like-button ${data.liked?'liked':''}" id="post-like" aria-pressed="${Boolean(data.liked)}" ${votingClosed?'disabled':''}><span aria-hidden="true">${data.liked?'♥':'♡'}</span> ${kind==='entries'?(data.liked?'Voted':'Vote'):(data.liked?'Liked':'Like')} <strong>${data.likes}</strong></button><span>${data.commentCount} ${data.commentCount===1?'comment':'comments'}</span>${votingClosed?'<span class="meta">Voting Closed</span>':''}</div><div id="social-message" aria-live="polite"></div><h2>Discussion</h2><p class="meta">${loaded.some(c=>c.isExample)?'Example comments and their initial like counts are illustrative.':'Comments and replies are public.'}</p>${currentUser?replyForm(null):link('/account?returnTo='+encodeURIComponent(location.hash.slice(1)),'Sign In to Join the Discussion','button outline')}<div class="comment-list">${tree()||'<p class="discussion-empty">No comments yet.</p>'}</div>${data.hasMore?'<button class="button outline" id="more-comments">Load More Comments</button>':''}</section>`;
  panel.querySelector('#post-like').onclick=()=>{
   if(!currentUser){go('/account?returnTo='+encodeURIComponent(location.hash.slice(1)));return;}
   withButton(panel.querySelector('#post-like'),async()=>{await api(endpoint+'/like',{method:'PUT',body:{liked:!Boolean(lastData.liked)}});await refreshCatalogue();await load(true,true);},'#social-message');
  };
  panel.querySelector('#more-comments')?.addEventListener('click',()=>withButton(panel.querySelector('#more-comments'),()=>load(false,true),'#social-message'));
  panel.querySelectorAll('[data-comment-like]').forEach(b=>b.onclick=()=>withButton(b,async()=>{await api('/comments/'+b.dataset.commentLike+'/like',{method:'PUT',body:{liked:b.getAttribute('aria-pressed')!=='true'}});await load(true,true);},'#social-message'));
  panel.querySelectorAll('[data-reply]').forEach(b=>b.onclick=()=>{const slot=panel.querySelector(`[data-reply-slot="${b.dataset.reply}"]`),open=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!open));slot.innerHTML=open?'':replyForm(b.dataset.reply);bindComments();slot.querySelector('textarea')?.focus();});
  panel.querySelectorAll('[data-delete-comment]').forEach(b=>b.onclick=()=>{if(!confirm('Delete this comment? Replies will remain.'))return;withButton(b,async()=>{await api('/comments/'+b.dataset.deleteComment,{method:'DELETE'});await load();},'#social-message');});
  for(const saved of savedDrafts){let form=panel.querySelector(`.public-comment-form[data-parent="${saved.parent}"]`);if(!form&&saved.parent){const slot=panel.querySelector(`[data-reply-slot="${saved.parent}"]`);if(slot){slot.innerHTML=replyForm(saved.parent);form=slot.querySelector('form');panel.querySelector(`[data-reply="${saved.parent}"]`)?.setAttribute('aria-expanded','true');}}if(form)form.elements.body.value=saved.body;}
  bindComments();
 }
 function bindComments(){panel.querySelectorAll('.public-comment-form').forEach(form=>{let id=newRequestId();form.onsubmit=e=>{e.preventDefault();const button=form.querySelector('button');withButton(button,async()=>{await api(endpoint+'/comments',{method:'POST',body:{id,body:form.elements.body.value,parent_id:form.dataset.parent||null}});await refreshCatalogue();await load();},'#social-message');};});}
 try{await load();}catch(error){if(visible())panel.innerHTML=note(error.message,true);}
}
function bindEngagement(){
 bindProfilePhoto();
 const profile=document.querySelector('#profile-form');if(profile){profile.querySelectorAll('input:not([type=checkbox]),textarea').forEach(i=>i.required=false);profile.onsubmit=e=>{e.preventDefault();withButton(profile.querySelector('button[type=submit]')||profile.querySelector('button:last-child'),async()=>{const data=new FormData(profile);await api('/profile',{method:'PUT',body:{...Object.fromEntries(data),categories:data.getAll('categories'),skills:data.getAll('skills'),discoverable:data.has('discoverable'),use_history:data.has('use_history')}});document.querySelector('#engagement-message').innerHTML=note('Profile saved.');},'#engagement-message');};document.querySelector('#clear-browsing').onclick=()=>withButton(document.querySelector('#clear-browsing'),async()=>{await api('/browsing',{method:'DELETE'});document.querySelector('#engagement-message').innerHTML=note('Browsing history cleared.');},'#engagement-message');}
 const create=document.querySelector('#challenge-form');if(create){const id=newRequestId();create.onsubmit=e=>{e.preventDefault();withButton(create.querySelector('button'),async()=>{const data=Object.fromEntries(new FormData(create));data.submission_deadline=new Date(data.submission_deadline).toISOString();data.voting_deadline=new Date(data.voting_deadline).toISOString();await api('/build-challenges',{method:'POST',body:{...data,id}});go('/build-challenges/'+id);},'#engagement-message');};}
 const entry=document.querySelector('#entry-form');if(entry)entry.onsubmit=e=>{e.preventDefault();withButton(entry.querySelector('button'),async()=>{await api('/build-challenges/'+entry.dataset.challenge+'/entry',{method:'PUT',body:{...Object.fromEntries(new FormData(entry)),id:entry.dataset.entry}});render(false);},'#engagement-message');};
 document.querySelector('[data-jump-entry]')?.addEventListener('click',e=>{e.preventDefault();document.querySelector('#submit-entry')?.scrollIntoView({behavior:'smooth'});document.querySelector('#e-title')?.focus({preventScroll:true});});
 const withdraw=document.querySelector('[data-withdraw-entry]');if(withdraw)withdraw.onclick=()=>{if(!confirm('Withdraw this entry from the challenge gallery?'))return;withButton(withdraw,async()=>{await api('/challenge-entries/'+withdraw.dataset.withdrawEntry,{method:'DELETE'});go('/build-challenges/'+withdraw.dataset.challenge);},'#engagement-message');};
 const introduction=document.querySelector('[data-introduction]');if(introduction)introduction.onclick=()=>{draft={key:'team',values:{affiliation:'',interest:'I would like an introduction to '+introduction.dataset.introduction+'.\nTopic: ',expertise:''}};go('/participate?mode=team');};
 const people=document.querySelector('#people-search');if(people)people.onsubmit=e=>{e.preventDefault();go('/people?q='+encodeURIComponent(people.elements.q.value));};
 document.querySelectorAll('#social-panel').forEach(mountDiscussion);
 document.querySelector('.overview-link')?.addEventListener('click',e=>{e.preventDefault();main.innerHTML=homeBase;main.insertAdjacentHTML('afterbegin',`<div class="wrap overview-return">${link('/','Back to My Marketplace','button outline')}</div>`);document.querySelector('.overview-return a').onclick=e=>{e.preventDefault();render();};});
}

const marketplaceRender=render;
render=function(focus=true){
 const sequence=++engagementSequence,{path,params}=getRoute();
 if(path==='/assistant'){history.replaceState(null,'','#'+(currentUser?'/manage':'/opportunities'));render(focus);return;}
 document.querySelector('[data-account-menu]')?.removeAttribute('open');
 if(path==='/engage'){history.replaceState(null,'','#/opportunities');render(focus);return;}
 const custom=path.startsWith('/build-challenges')||path.startsWith('/entries/')||path==='/profile'||path==='/for-you'||path==='/people'||path.startsWith('/people/');
 if(!ready||!custom){marketplaceRender(focus);if(ready){const match=path.match(/^\/(opportunities|projects|communities)\/([^/]+)$/);if(match&&document.querySelector('.detail-body')){document.querySelector('.detail-body').insertAdjacentHTML('beforeend',`<div id="social-panel" data-kind="records" data-record="${esc(match[2])}"></div>`);mountDiscussion(document.querySelector('#social-panel'));document.querySelector('[data-discussion-jump]')?.addEventListener('click',()=>{const panel=document.querySelector('#social-panel');panel.scrollIntoView({behavior:'smooth'});panel.setAttribute('tabindex','-1');panel.focus({preventScroll:true});});if(match[1]==='opportunities')mountCollaborators(match[2]);if(currentUser)api('/browsing',{method:'POST',body:{record_id:match[2]}}).catch(()=>{});}if(path==='/'){if(currentUser)main.insertAdjacentHTML('beforeend',`<div class="wrap home-member-links">${link('/activity','My Activity →','button outline')}</div>`);}}return;}
 ++viewSequence;main.innerHTML=loading();document.querySelector('nav').classList.remove('open');document.querySelector('.menu').setAttribute('aria-expanded','false');
 document.querySelectorAll('nav a').forEach(a=>{const target=a.hash.slice(1),active=target==='/'?path==='/':target==='/opportunities'&&(path.startsWith('/build-challenges')||path.startsWith('/entries/'))||path===target||path.startsWith(target+'/');a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 const work=path==='/for-you'?engagementHome():path==='/profile'?profilePage():path==='/people'?peoplePage(params):path.startsWith('/people/')?personPage(path.split('/')[2]):path==='/build-challenges/new'?Promise.resolve(challengeForm()):path==='/build-challenges'?challengesPage():path.startsWith('/entries/')?entryDetail(path.split('/')[2]):challengeDetail(path.split('/')[2]);
 work.then(html=>{if(sequence!==engagementSequence)return;main.innerHTML=html;document.title=(main.querySelector('h1')?.textContent||'Marketplace')+' | UB AI Innovation Marketplace';bindEngagement();if(focus){window.scrollTo(0,0);main.focus();}}).catch(error=>{if(sequence===engagementSequence)main.innerHTML=heading('Marketplace','Unable to Load This Page')+`<div class="wrap section">${note(error.message,true)}<button class="button" id="retry-engagement">Try Again</button></div>`;document.querySelector('#retry-engagement')?.addEventListener('click',()=>render(false));});
};
for(const kind of ['opportunities','projects','communities']){
 const base=kind==='opportunities'?oppCard:kind==='projects'?projectCard:groupCard;
 const wrapped=r=>base(r).replace('<a class="card-bottom"',`<div class="card-engagement"><span>♡ ${r.likes||0} ${(r.likes||0)===1?'like':'likes'}</span><a href="#/${kind}/${r.id}">${r.comments||0} ${(r.comments||0)===1?'comment':'comments'}</a></div><a class="card-bottom"`);
 if(kind==='opportunities')oppCard=wrapped;else if(kind==='projects')projectCard=wrapped;else groupCard=wrapped;
}

function avatar(name,photo,size=''){
 const initials=String(name||'?').trim().split(/\s+/).slice(0,2).map(w=>w[0]).join('').toUpperCase();
 const url=photo?.startsWith('/api/avatars/')?(location.pathname.startsWith('/ai-marketplace')?'/ai-marketplace':'')+photo:'';
 return `<span class="avatar ${size}"><span aria-hidden="true">${esc(initials)}</span>${url?`<img src="${esc(url)}" alt="" loading="lazy">`:''}</span>`;
}
document.addEventListener('error',event=>{if(event.target.matches?.('.avatar img'))event.target.remove();},true);
async function preparePortrait(file){
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw new Error('Choose a JPEG, PNG or WebP image under 10 MB.');
 const source=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('The photo could not be read.'));reader.onload=()=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('The photo could not be read.'));image.src=reader.result;};reader.readAsDataURL(file);});
 const canvas=document.createElement('canvas');canvas.width=canvas.height=192;const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,192,192);const side=Math.min(source.width,source.height);context.drawImage(source,(source.width-side)/2,(source.height-side)/2,side,side,0,0,192,192);
 let image=canvas.toDataURL('image/jpeg',0.8);if(image.length>32000)image=canvas.toDataURL('image/jpeg',0.5);if(image.length>32000)throw new Error('This photo could not be reduced enough. Try a smaller image.');return image;
}
function bindProfilePhoto(){
 const input=document.querySelector('#profile-photo-input');if(!input)return;
 input.onchange=async()=>{if(!input.files[0])return;input.disabled=true;document.querySelector('#photo-message').textContent='Uploading…';try{const image=await preparePortrait(input.files[0]);const result=await api('/profile/photo',{method:'PUT',body:{image}});document.querySelector('#profile-photo-preview').innerHTML=avatar(currentUser.name,result.photo+'?v='+Date.now(),'large');document.querySelector('#photo-message').textContent='Photo saved.';}catch(error){document.querySelector('#photo-message').textContent=error.message;}finally{input.disabled=false;input.value='';}};
 document.querySelector('#remove-profile-photo').onclick=()=>withButton(document.querySelector('#remove-profile-photo'),async()=>{await api('/profile/photo',{method:'DELETE'});document.querySelector('#profile-photo-preview').innerHTML=avatar(currentUser.name,null,'large');document.querySelector('#photo-message').textContent='Photo removed.';},'#photo-message');
 document.querySelector('#hide-participation').onclick=()=>withButton(document.querySelector('#hide-participation'),async()=>{await api('/profile/participation',{method:'DELETE'});document.querySelector('#engagement-message').innerHTML=note('Your name is hidden on all public collaborator lists.');},'#engagement-message');
}
async function mountCollaborators(id){
 const aside=document.querySelector('.aside');if(!aside)return;
 const panel=document.createElement('section');panel.className='listing-collaborators';aside.append(panel);
 const endpoint='/listing-collaborators/'+encodeURIComponent(id);
 async function load(){
  const data=await api(endpoint);if(!panel.isConnected)return;
  panel.innerHTML=`<h3>Interested Collaborators</h3><div class="collaborator-roster">${data.items.length?data.items.map(p=>`<div class="person-row">${avatar(p.name,p.photo)}<div>${p.profileAvailable?link('/people/'+p.id,esc(p.name),'person-name'):`<strong class="person-name">${esc(p.name)}</strong>`}<p>${esc(p.role)||'Member'}</p></div></div>`).join(''):'<p class="meta">No public profiles yet.</p>'}</div>${data.canShow?`<div class="participation-visibility"><label class="check-row"><input type="checkbox" id="show-on-listing" ${data.visible?'checked':''}><span>Show Me on This Listing</span></label><small>Your name, role and photo will be public. Your inquiry stays private.</small><div id="roster-message" role="status"></div></div>`:''}${data.isOwner?`<div class="owner-matching"><h3>Suggested Collaborators</h3><p>Find people whose skills and interests fit this opportunity.</p><button class="button outline" id="find-collaborators" data-pending-label="Finding Matches…">Find Collaborators</button><div id="matching-results"></div></div>`:''}`;
  const toggle=panel.querySelector('#show-on-listing');if(toggle)toggle.onchange=async()=>{toggle.disabled=true;try{await api(endpoint+'/visibility',{method:'PUT',body:{visible:toggle.checked}});await load();}catch(error){toggle.checked=!toggle.checked;panel.querySelector('#roster-message').innerHTML=note(error.message,true)+link('/profile','Edit My Profile');}finally{toggle.disabled=false;}};
  if(data.isOwner){
   const matches=panel.querySelector('#matching-results');
   const draw=result=>{if(!matches.isConnected)return;matches.innerHTML=`<p class="meta match-method">${result.mode==='ai'?'AI-Suggested Matches':'Profile Matches'}</p>${result.message?`<p class="meta" role="status">${esc(result.message)}</p>`:''}${result.items.length?result.items.map(p=>`<article class="match-card"><div class="person-row">${avatar(p.name,p.photo)}<div>${link('/people/'+p.id,esc(p.name),'person-name')}<p>${esc(p.affiliation)||'Member'}</p></div></div><p class="match-reason">${esc(p.reason)}</p>${p.skills?.length?chips(p.skills.slice(0,3)):''}${link('/people/'+p.id,'View Profile →','text-link')}</article>`).join(''):`<p class="meta">${result.candidateCount===0?'No other discoverable profiles are available yet.':'No suitable matches found yet.'}</p>`}`; 
   };
   api(endpoint+'/recommendations').then(result=>{if(result.items.length)draw(result);}).catch(()=>{});
   let requestId=newRequestId();panel.querySelector('#find-collaborators').onclick=()=>withButton(panel.querySelector('#find-collaborators'),async()=>{matches.innerHTML='<p class="meta" role="status">Checking discoverable profiles against this listing…</p>';try{draw(await api(endpoint+'/recommendations',{method:'POST',body:{id:requestId}}));}finally{requestId=newRequestId();}},'#matching-results');
  }
 }
 try{await load();}catch(error){if(panel.isConnected)panel.innerHTML=`<h3>Interested Collaborators</h3><p class="meta">${esc(error.message)}</p>`;}
}
