'use strict';
const expertiseChoices=['Python','Data Analysis','AI and Machine Learning','Design','Project Management','Domain Knowledge','Communication'];
const loginPrompt=()=>`<div class="wrap section">${link('/account?returnTo='+encodeURIComponent(location.hash.slice(1)),'Sign In to Participate','button')}</div>`;
const exampleTag=flag=>flag?'<span class="example-badge">Example</span>':'';
const dateOnly=value=>new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
const challengeState=c=>new Date(c.submission_deadline)>new Date()?'Open for Entries':new Date(c.voting_deadline)>new Date()?'Voting Open':'Completed';
let engagementSequence=0,assistantResult=null,engagementUserId=null;
function miniCard(r){return `<article class="card recommendation">${exampleTag(r.example)}<span class="tag">${esc(r.kind==='opportunities'?'Opportunity':r.kind==='projects'?'Project':'Community')}</span><h3>${link('/'+r.kind+'/'+r.id,esc(r.title),'')}</h3><p>${esc(r.summary||'')}</p>${r.reasons?.length?`<p class="recommendation-reason">${esc(r.reasons.join(' · '))}</p>`:''}${link('/'+r.kind+'/'+r.id,'View Details →','card-bottom')}</article>`;}
function challengeCard(c){return `<article class="card challenge-card"><div class="card-top">${exampleTag(c.is_example)}<span class="tag">${challengeState(c)}</span></div><h3>${link('/build-challenges/'+c.id,esc(c.title),'')}</h3><p>${esc(c.summary)}</p><div class="challenge-facts"><span>Entries close <strong>${dateOnly(c.submission_deadline)}</strong></span><span><strong>${c.entries}</strong> entries</span></div>${link('/build-challenges/'+c.id,'View Challenge →','card-bottom')}</article>`;}
async function engagementHome(){
 const data=await api('/recommendations');
 return heading('My Marketplace','Hello, '+esc(currentUser.name))+`<section class="wrap engagement-home"><div class="workspace-toolbar"><div class="action-links">${link('/profile','Edit My Profile','button outline')}${link('/activity','My Activity','button outline')}${link('/manage','My Listings','button outline')}</div>${link('/','Marketplace Overview','text-link overview-link')}</div><div class="engagement-launch"><div><span class="tag">AI Assistant</span><h2>What Would You Like to Work On?</h2><p>Explore an idea, find collaborators or prepare a project brief.</p>${link('/assistant','Open Assistant →','button')}</div><div class="launch-links">${link('/build-challenges','Build Challenges <span>Browse briefs and submit an entry →</span>','')}${link('/people','Find People <span>Explore discoverable member profiles →</span>','')}${link('/engage','Popular Posts <span>See the community leaderboard →</span>','')}</div></div><div class="section-head"><h2>Recommended for You</h2>${link('/opportunities','All Opportunities →','text-link')}</div>${data.items.length?`<div class="grid two">${data.items.map(miniCard).join('')}</div>`:`<div class="empty"><h3>${data.profile.categories.length||data.profile.interests?'No Matches Yet':'Set Your Interests'}</h3><p>${data.profile.categories.length||data.profile.interests?'Browse the directory or adjust your profile to explore more options.':'Choose categories and skills to personalize this page.'}</p>${link('/profile','Edit Profile','button outline')}</div>`}<p class="meta recommendation-note">Recommendations use your profile${data.profile.use_history?' and up to 30 days of marketplace browsing':''}. ${link('/profile','Manage Preferences','text-link')}</p></section>`;
}
async function explorePage(params){
 const period=params.get('period')==='month'?'month':'all';const [board,challenges]=await Promise.all([api('/leaderboard?period='+period),api('/build-challenges')]);
 let rank=0,previous=-1;
 return heading('Explore','Explore the Marketplace')+`<section class="wrap engagement-page"><div class="engagement-launch compact"><div><span class="tag">Build Challenges</span><h2>Open Build Challenges</h2><p>Submit a demonstration individually or as a team.</p>${link('/build-challenges','View Challenges →','button')}</div><div class="launch-links">${link('/people','Find People <span>Profiles, interests and skills →</span>','')}${link('/assistant','AI Assistant <span>Explore ideas and collaboration options →</span>','')}</div></div><div class="section-head"><div><h2>Post Leaderboard</h2><p>Ranked by likes on posts.</p></div><div class="tabs">${link('/engage?period=all','All Time',period==='all'?'selected':'')}${link('/engage?period=month','Last 30 Days',period==='month'?'selected':'')}</div></div><div class="leaderboard">${board.items.length?board.items.map((r,i)=>{if(r.likes!==previous)rank=i+1;previous=r.likes;return `<a class="leaderboard-row" href="#/${r.kind}/${r.id}"><span class="rank">${rank}</span><div><span class="meta">${r.kind==='opportunities'?'Opportunity':r.kind==='projects'?'Project':'Community'}</span><h3>${esc(r.title)}</h3>${exampleTag(r.example)}</div><span class="ranking-score">${r.likes}<small>${r.likes===1?'like':'likes'}</small></span></a>`;}).join(''):'<div class="empty"><h3>No Ranked Posts Yet</h3><p>Like a post to add it to the leaderboard.</p>'+link('/opportunities','Browse Opportunities','button outline')+'</div>'}</div><div class="section-head"><h2>Build Challenges</h2>${link('/build-challenges','View All →')}</div><div class="grid two">${challenges.items.slice(0,2).map(challengeCard).join('')}</div></section>`;
}
function formField(name,label,value='',type='text',max=3000){return `<div class="field"><label for="e-${name}">${label}</label>${type==='textarea'?`<textarea id="e-${name}" name="${name}" maxlength="${max}" required>${esc(value)}</textarea>`:`<input id="e-${name}" name="${name}" type="${type}" maxlength="${max}" value="${esc(value)}" ${name==='demo_url'?'':'required'}>`}</div>`;}
async function challengesPage(){const data=await api('/build-challenges');return heading('Build Challenges','Build Challenges','Time-bound briefs with entry galleries and community voting.')+`<section class="wrap engagement-page">${currentUser?.isAdmin?`<div class="workspace-toolbar">${link('/build-challenges/new','Create a Build Challenge','button')}</div>`:''}<div class="grid two">${data.items.map(challengeCard).join('')}</div></section>`;}
function challengeForm(){return heading('Build Challenges','Create a Build Challenge','Published challenges appear immediately.')+(currentUser?.isAdmin?`<form id="challenge-form" class="form-wrap"><div id="engagement-message"></div>${formField('title','Title','','text',160)}${formField('summary','Summary','','textarea',500)}${formField('brief','Challenge Brief','','textarea',6000)}${formField('criteria','Submission Requirements','','textarea')}${formField('submission_deadline','Entry Deadline','','datetime-local')}${formField('voting_deadline','Voting Deadline','','datetime-local')}<p class="meta">Times use your device’s local time zone. Entries are ranked by community votes.</p><button class="button">Publish Challenge</button></form>`:loginPrompt());}
async function challengeDetail(id){
 const c=await api('/build-challenges/'+encodeURIComponent(id)),open=new Date(c.submission_deadline)>new Date(),entry=c.ownEntry;let rank=0,prev=-1;
 return heading('Build Challenges',esc(c.title),exampleTag(c.is_example)+esc(c.summary),'/build-challenges')+`<div class="wrap detail-layout"><div class="detail-body">${section('Challenge Brief',`<p class="preserve">${esc(c.brief)}</p>`)}${section('Submission Requirements',`<p class="preserve">${esc(c.criteria)}</p>`)}${section('Community-Choice Leaderboard',`<p>Ranked by votes from signed-in members.</p><div class="leaderboard">${c.entries.length?c.entries.map((e,i)=>{if(e.likes!==prev)rank=i+1;prev=e.likes;return `<a class="leaderboard-row" href="#/entries/${e.id}"><span class="rank">${e.likes?rank:'—'}</span><div><h3>${esc(e.title)}</h3><p>${esc(e.team)}</p></div><span class="ranking-score">${e.likes}<small>votes</small></span></a>`;}).join(''):'<div class="empty"><h3>No Entries Yet</h3><p>Submitted entries will appear here.</p></div>'}</div>`)}${currentUser&&open?`<section id="submit-entry"><h2>${entry?.status==='published'?'Edit Your Entry':'Submit an Entry'}</h2><p>One entry per account per challenge. Your entry appears in the public gallery.</p><form id="entry-form" data-challenge="${c.id}" data-entry="${entry?.id||newRequestId()}"><div id="engagement-message"></div>${formField('title','Entry Title',entry?.title||'','text',160)}${formField('team','Team or Participant Name',entry?.team||currentUser.name,'text',200)}${formField('summary','What You Built',entry?.summary||'','textarea')}${formField('demo_url','Demo or Repository Link (Optional)',entry?.demo_url||'','url',1500)}<button class="button">${entry?.status==='published'?'Save Entry':'Publish Entry'}</button></form></section>`:''}</div><aside class="aside"><span class="tag">${challengeState(c)}</span><dl><dt>Entry Deadline</dt><dd>${esc(stamp(c.submission_deadline))}</dd><dt>Voting Deadline</dt><dd>${esc(stamp(c.voting_deadline))}</dd><dt>Entries</dt><dd>${c.entries.length}</dd></dl>${open?(currentUser?'<a class="button" href="#submit-entry" data-jump-entry>Submit or Edit Entry</a>':link('/account?returnTo='+encodeURIComponent('/build-challenges/'+id),'Sign In to Submit','button')):''}${entry?.status==='published'?link('/entries/'+entry.id,'View Your Entry','button outline'):''}</aside></div>`;
}
async function entryDetail(id){const e=await api('/challenge-entries/'+encodeURIComponent(id));return heading('Challenge Entry',esc(e.title),esc(e.team),'/build-challenges/'+e.challenge_id)+`<div class="wrap detail-layout"><div class="detail-body">${section('Entry Overview',`<p class="preserve">${esc(e.summary)}</p>${e.demo_url?`<a href="${esc(e.demo_url)}" target="_blank" rel="noopener noreferrer" class="button outline">Open Demo or Repository ↗</a>`:''}`)}<div id="social-panel" data-kind="entries" data-record="${e.id}" data-voting-closed="${new Date(e.voting_deadline)<=new Date()}"></div></div><aside class="aside"><h3>${esc(e.challenge_title)}</h3><p>Submitted by ${esc(e.owner_name)}</p>${link('/build-challenges/'+e.challenge_id,'View Challenge','button outline')}${currentUser?.id===e.owner_id||currentUser?.isAdmin?`<div id="engagement-message"></div><button class="button outline" data-withdraw-entry="${e.id}" data-challenge="${e.challenge_id}">Withdraw Entry</button>`:''}</aside></div>`;}
async function profilePage(){
 if(!currentUser)return heading('Profile','My Profile')+loginPrompt();const p=await api('/profile');
 const choices=(name,label,values,selected)=>`<fieldset class="field skill-picker"><legend>${label}</legend><div class="skill-options">${values.map((v,i)=>`<label class="skill-option"><input type="checkbox" name="${name}" value="${esc(v)}" ${selected.includes(v)?'checked':''}><span>${esc(v)}</span></label>`).join('')}</div></fieldset>`;
 return heading('My Marketplace','My Profile','Choose what you want to explore and what you can contribute.')+`<form class="form-wrap" id="profile-form"><div id="engagement-message"></div>${formField('affiliation','Role and Affiliation',p.affiliation,'text',200)}${choices('categories','Areas of Interest',collaborationCategories,p.categories)}${choices('skills','Skills and Experience',expertiseChoices,p.skills)}${formField('interests','Topics or Goals',p.interests,'textarea',1000)}${formField('availability','Availability',p.availability,'text',200)}<div class="profile-settings"><label class="check-row"><input type="checkbox" name="discoverable" ${p.discoverable?'checked':''}><span><strong>Make My Profile Discoverable</strong><small>Other signed-in members and the AI assistant can find your name, affiliation, interests, skills and availability.</small></span></label><label class="check-row"><input type="checkbox" name="use_history" ${p.use_history?'checked':''}><span><strong>Use My Browsing for Recommendations</strong><small>Use listings you view on this site for up to 30 days. Turning this off clears your browsing history.</small></span></label><button type="button" class="text-link" id="clear-browsing">Clear Browsing History</button></div><button class="button" type="submit">Save Profile</button></form>`;
}
async function peoplePage(params){if(!currentUser)return heading('People','Find People')+loginPrompt();const q=params.get('q')||'',data=await api('/people?q='+encodeURIComponent(q));return heading('People','Find People','Members who have made their profiles discoverable.')+`<section class="wrap engagement-page"><form id="people-search" class="people-search"><label for="people-q" class="sr-only">Search interests or skills</label><input id="people-q" name="q" value="${esc(q)}" placeholder="Search interests or skills"><button class="button">Search</button>${link('/profile','Edit My Profile','button outline')}</form><div class="grid two">${data.items.length?data.items.map(p=>`<article class="card"><span class="tag">Member</span><h3><a href="${esc(p.url)}">${esc(p.name)}</a></h3><p>${esc(p.affiliation)}</p>${chips(p.skills)}<p>${esc(p.interests)}</p><p class="meta">${esc(p.availability)}</p><a class="card-bottom" href="${esc(p.url)}">View Profile →</a></article>`).join(''):'<div class="empty"><h3>No Matching Profiles Yet</h3><p>Members appear here when they make their profile discoverable.</p></div>'}</div></section>`;}
async function personPage(id){if(!currentUser)return heading('People','Member Profile')+loginPrompt();const p=await api('/people/'+encodeURIComponent(id));return heading('People',esc(p.name),esc(p.affiliation),'/people')+`<section class="wrap engagement-page"><div class="profile-detail">${section('Interests',`<p>${esc(p.interests)}</p>`)}${section('Skills and Experience',chips(p.skills))}${section('Availability',`<p>${esc(p.availability)||'Not specified'}</p>`)}${section('Published Listings',p.listings.length?p.listings.map(r=>link('/'+r.kind+'/'+r.id,esc(r.title),'choice')).join(''):'<p>No published listings.</p>')}<button class="button outline" data-introduction="${esc(p.name)}">Request an Introduction</button></div></section>`;}
const toolLabels={search_marketplace:'Searched Marketplace',find_collaborators:'Searched Discoverable Profiles',find_resources:'Checked Resources and Build Challenges'};
function assistantOutput(result){return `<article class="assistant-answer"><span class="tag">AI-Generated Suggestions</span><div class="preserve">${esc(result.answer)}</div>${result.trace?.length?`<details><summary>Sources Checked</summary><ol>${result.trace.map(t=>`<li>${toolLabels[t.tool]}${t.query?' · '+esc(t.query):''} (${t.found} results)</li>`).join('')}</ol>${result.sources.map(s=>`<a class="source-link" href="${esc(s.url)}" ${s.url.startsWith('https:')?'target="_blank" rel="noopener noreferrer"':''}>${esc(s.title)} ${s.example?'· Example':''} ↗</a>`).join('')}</details>`:''}${result.brief?`<div class="field"><label for="assistant-brief">Draft Project Brief</label><textarea id="assistant-brief" maxlength="3000" rows="10">${esc(result.brief)}</textarea></div><button class="button outline" id="use-assistant-brief">Use in an Opportunity Draft</button>`:''}</article>`;}
async function assistantPage(){if(!currentUser)return heading('AI Assistant','Explore a Project or Collaboration')+loginPrompt();const data=await api('/assistant');return heading('AI Assistant','Explore a Project or Collaboration','Find connections, investigate an idea or prepare a project brief.')+`<section class="wrap engagement-page assistant-layout"><div><form id="assistant-form"><div id="engagement-message"></div><div class="field"><label for="assistant-goal">What Would You Like to Work On?</label><textarea id="assistant-goal" name="goal" maxlength="2000" minlength="10" required placeholder="Describe your goal, the help you need or an idea you want to develop."></textarea></div><div class="prompt-options">${['Find collaborators for my interests','Help me develop a project idea','Find resources and opportunities for my goals'].map(t=>`<button type="button" data-prompt="${esc(t)}">${esc(t)}</button>`).join('')}</div><p class="meta">Uses your request and profile with published listings and discoverable profiles. Powered by Cloudflare Workers AI.</p><button type="submit" data-pending-label="Exploring…" class="button" ${data.available?'':'disabled'}>Explore with AI</button>${!data.available?'<p class="notice">The AI service is not connected in this environment.</p>':''}</form><div id="assistant-output" aria-live="polite">${assistantResult?assistantOutput(assistantResult):''}</div></div><aside class="assistant-history"><h2>Recent Explorations</h2>${data.items.length?data.items.map((r,i)=>`<button class="history-item" data-run="${r.id}" ${r.status==='completed'?'':'disabled'}><strong>${esc(r.goal)}</strong><span>${r.status==='completed'?dateOnly(r.created_at):r.status==='running'?'In Progress':'Could Not Complete'}</span></button>`).join(''):'<p>Your explorations will appear here.</p>'}${link('/profile','Edit My Profile →')}</aside></section>`;}
async function mountDiscussion(panel){
 const {kind,record}=panel.dataset,endpoint='/engagement/'+kind+'/'+encodeURIComponent(record);let loaded=[],lastData;
 const visible=()=>panel.isConnected;
 const replyForm=parent=>`<form class="public-comment-form" data-parent="${parent||''}"><label for="comment-${parent||'new'}">${parent?'Your Reply':'Add a Comment'}</label><textarea id="comment-${parent||'new'}" name="body" maxlength="2000" required rows="3"></textarea><button class="button outline">${parent?'Post Reply':'Post Comment'}</button><div class="comment-message"></div></form>`;
 const comment=c=>`<article class="public-comment ${c.parent_id?'reply':''}" id="comment-${c.id}-item"><div class="comment-byline"><strong>${c.deleted?'Deleted Comment':esc(c.author_name)}</strong><time>${esc(stamp(c.created_at))}</time></div><p class="preserve">${c.deleted?'This comment was removed.':esc(c.body)}</p><div class="comment-actions">${!c.parent_id&&currentUser?`<button data-reply="${c.id}" aria-expanded="false">Reply</button>`:''}${c.canDelete?`<button data-delete-comment="${c.id}">Delete</button>`:''}</div><div class="reply-slot" data-reply-slot="${c.id}"></div></article>`;
 async function load(reset=true,preserveDrafts=false){
  const savedDrafts=preserveDrafts?[...panel.querySelectorAll('.public-comment-form')].map(form=>({parent:form.dataset.parent,body:form.elements.body.value})):[];
  const data=await api(endpoint+'?offset='+(reset?0:loaded.length));if(!visible())return;lastData=data;loaded=reset?data.comments:[...loaded,...data.comments];
  const votingClosed=kind==='entries'&&panel.dataset.votingClosed==='true';
  panel.innerHTML=`<section class="discussion"><div class="social-toolbar"><button class="like-button ${data.liked?'liked':''}" id="post-like" aria-pressed="${Boolean(data.liked)}" ${votingClosed?'disabled':''}><span aria-hidden="true">${data.liked?'♥':'♡'}</span> ${kind==='entries'?(data.liked?'Voted':'Vote'):(data.liked?'Liked':'Like')} <strong>${data.likes}</strong></button><span>${data.commentCount} ${data.commentCount===1?'comment':'comments'}</span>${votingClosed?'<span class="meta">Voting Closed</span>':''}</div><div id="social-message" aria-live="polite"></div><h2>Discussion</h2><p class="meta">Comments and replies are public.</p>${currentUser?replyForm(null):link('/account?returnTo='+encodeURIComponent(location.hash.slice(1)),'Sign In to Join the Discussion','button outline')}<div class="comment-list">${loaded.filter(c=>!c.parent_id).map(c=>comment(c)+`<div class="comment-replies">${loaded.filter(r=>r.parent_id===c.id).map(comment).join('')}</div>`).join('')||'<p class="discussion-empty">No comments yet.</p>'}</div>${data.hasMore?'<button class="button outline" id="more-comments">Load More Comments</button>':''}</section>`;
  panel.querySelector('#post-like').onclick=()=>{
   if(!currentUser){go('/account?returnTo='+encodeURIComponent(location.hash.slice(1)));return;}
   withButton(panel.querySelector('#post-like'),async()=>{await api(endpoint+'/like',{method:'PUT',body:{liked:!Boolean(lastData.liked)}});await refreshCatalogue();await load(true,true);},'#social-message');
  };
  panel.querySelector('#more-comments')?.addEventListener('click',()=>withButton(panel.querySelector('#more-comments'),()=>load(false,true),'#social-message'));
  panel.querySelectorAll('[data-reply]').forEach(b=>b.onclick=()=>{const slot=panel.querySelector(`[data-reply-slot="${b.dataset.reply}"]`),open=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!open));slot.innerHTML=open?'':replyForm(b.dataset.reply);bindComments();slot.querySelector('textarea')?.focus();});
  panel.querySelectorAll('[data-delete-comment]').forEach(b=>b.onclick=()=>{if(!confirm('Delete this comment? Replies will remain.'))return;withButton(b,async()=>{await api('/comments/'+b.dataset.deleteComment,{method:'DELETE'});await load();},'#social-message');});
  for(const saved of savedDrafts){let form=panel.querySelector(`.public-comment-form[data-parent="${saved.parent}"]`);if(!form&&saved.parent){const slot=panel.querySelector(`[data-reply-slot="${saved.parent}"]`);if(slot){slot.innerHTML=replyForm(saved.parent);form=slot.querySelector('form');panel.querySelector(`[data-reply="${saved.parent}"]`)?.setAttribute('aria-expanded','true');}}if(form)form.elements.body.value=saved.body;}
  bindComments();
 }
 function bindComments(){panel.querySelectorAll('.public-comment-form').forEach(form=>{let id=newRequestId();form.onsubmit=e=>{e.preventDefault();const button=form.querySelector('button');withButton(button,async()=>{await api(endpoint+'/comments',{method:'POST',body:{id,body:form.elements.body.value,parent_id:form.dataset.parent||null}});await refreshCatalogue();await load();},'#social-message');};});}
 try{await load();}catch(error){if(visible())panel.innerHTML=note(error.message,true);}
}
function bindEngagement(){
 const profile=document.querySelector('#profile-form');if(profile){profile.querySelectorAll('input:not([type=checkbox]),textarea').forEach(i=>i.required=false);profile.onsubmit=e=>{e.preventDefault();withButton(profile.querySelector('button[type=submit]')||profile.querySelector('button:last-child'),async()=>{const data=new FormData(profile);await api('/profile',{method:'PUT',body:{...Object.fromEntries(data),categories:data.getAll('categories'),skills:data.getAll('skills'),discoverable:data.has('discoverable'),use_history:data.has('use_history')}});document.querySelector('#engagement-message').innerHTML=note('Profile saved.');},'#engagement-message');};document.querySelector('#clear-browsing').onclick=()=>withButton(document.querySelector('#clear-browsing'),async()=>{await api('/browsing',{method:'DELETE'});document.querySelector('#engagement-message').innerHTML=note('Browsing history cleared.');},'#engagement-message');}
 const create=document.querySelector('#challenge-form');if(create){const id=newRequestId();create.onsubmit=e=>{e.preventDefault();withButton(create.querySelector('button'),async()=>{const data=Object.fromEntries(new FormData(create));data.submission_deadline=new Date(data.submission_deadline).toISOString();data.voting_deadline=new Date(data.voting_deadline).toISOString();await api('/build-challenges',{method:'POST',body:{...data,id}});go('/build-challenges/'+id);},'#engagement-message');};}
 const entry=document.querySelector('#entry-form');if(entry)entry.onsubmit=e=>{e.preventDefault();withButton(entry.querySelector('button'),async()=>{await api('/build-challenges/'+entry.dataset.challenge+'/entry',{method:'PUT',body:{...Object.fromEntries(new FormData(entry)),id:entry.dataset.entry}});render(false);},'#engagement-message');};
 document.querySelector('[data-jump-entry]')?.addEventListener('click',e=>{e.preventDefault();document.querySelector('#submit-entry')?.scrollIntoView({behavior:'smooth'});document.querySelector('#e-title')?.focus({preventScroll:true});});
 const withdraw=document.querySelector('[data-withdraw-entry]');if(withdraw)withdraw.onclick=()=>{if(!confirm('Withdraw this entry from the challenge gallery?'))return;withButton(withdraw,async()=>{await api('/challenge-entries/'+withdraw.dataset.withdrawEntry,{method:'DELETE'});go('/build-challenges/'+withdraw.dataset.challenge);},'#engagement-message');};
 const introduction=document.querySelector('[data-introduction]');if(introduction)introduction.onclick=()=>{draft={key:'team',values:{affiliation:'',interest:'I would like an introduction to '+introduction.dataset.introduction+'.\nTopic: ',expertise:''}};go('/participate?mode=team');};
 const people=document.querySelector('#people-search');if(people)people.onsubmit=e=>{e.preventDefault();go('/people?q='+encodeURIComponent(people.elements.q.value));};
 const assistant=document.querySelector('#assistant-form');if(assistant){let runId=newRequestId(),priorGoal='';assistant.onsubmit=e=>{e.preventDefault();const goal=assistant.elements.goal.value;if(goal!==priorGoal){runId=newRequestId();priorGoal=goal;}withButton(assistant.querySelector('button[type=submit]')||assistant.querySelector('button:last-of-type'),async()=>{document.querySelector('#assistant-output').innerHTML='<p class="notice" role="status">Exploring your request and checking relevant sources…</p>';let data;try{data=await api('/assistant',{method:'POST',body:{id:runId,goal}});}catch(error){document.querySelector('#assistant-output')?.replaceChildren();runId=newRequestId();throw error;}if(getRoute().path!=='/assistant')return;if(data.status!=='completed'){document.querySelector('#assistant-output').innerHTML=note(data.status==='running'?'This exploration is still in progress. Reload this page shortly to check Recent Explorations.':'This exploration could not be completed. Submit again to retry.',data.status==='failed');if(data.status==='failed')runId=newRequestId();return;}assistantResult=data.result;document.querySelector('#assistant-output').innerHTML=assistantOutput(data.result);bindAssistantBrief();runId=newRequestId();},'#engagement-message');};
  document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{assistant.elements.goal.value=b.dataset.prompt;assistant.elements.goal.focus();});
  document.querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>withButton(b,async()=>{const data=await api('/assistant'),item=data.items.find(r=>r.id===b.dataset.run);if(item?.result){assistantResult=item.result;document.querySelector('#assistant-output').innerHTML=assistantOutput(item.result);bindAssistantBrief();}},'#engagement-message'));
 }
 bindAssistantBrief();document.querySelectorAll('#social-panel').forEach(mountDiscussion);
 document.querySelector('.overview-link')?.addEventListener('click',e=>{e.preventDefault();main.innerHTML=homeBase;main.insertAdjacentHTML('afterbegin',`<div class="wrap overview-return">${link('/','Back to My Marketplace','button outline')}</div>`);document.querySelector('.overview-return a').onclick=e=>{e.preventDefault();render();};});
}
function bindAssistantBrief(){const button=document.querySelector('#use-assistant-brief');if(button)button.onclick=()=>{const brief=document.querySelector('#assistant-brief').value;draft={key:'challenge',values:{type:'seedling',category:'Research',impact:'Novel Ideas',title:'',unit:'',problem:brief}};go('/participate?mode=challenge');};}
const marketplaceRender=render;
render=function(focus=true){
 if(engagementUserId!==currentUser?.id){assistantResult=null;engagementUserId=currentUser?.id;}
 const sequence=++engagementSequence,{path,params}=getRoute();
 const custom=path==='/engage'||path.startsWith('/build-challenges')||path.startsWith('/entries/')||path==='/profile'||path==='/assistant'||path==='/people'||path.startsWith('/people/')||path==='/'&&currentUser;
 if(!ready||!custom){marketplaceRender(focus);if(ready){const match=path.match(/^\/(opportunities|projects|communities)\/([^/]+)$/);if(match&&document.querySelector('.detail-body')){document.querySelector('.detail-body').insertAdjacentHTML('beforeend',`<div id="social-panel" data-kind="records" data-record="${esc(match[2])}"></div>`);mountDiscussion(document.querySelector('#social-panel'));if(currentUser)api('/browsing',{method:'POST',body:{record_id:match[2]}}).catch(()=>{});}if(path==='/')main.insertAdjacentHTML('beforeend',`<section class="wrap home-explore"><h2>More Ways to Participate</h2><div class="home-explore-links">${link('/build-challenges','Build Challenges →','button outline')}${link('/engage','Post Leaderboard →','button outline')}${link('/people','Find People →','button outline')}${link('/assistant','AI Assistant →','button outline')}</div></section>`);}return;}
 ++viewSequence;main.innerHTML=loading();document.querySelector('nav').classList.remove('open');document.querySelector('.menu').setAttribute('aria-expanded','false');
 document.querySelectorAll('nav a').forEach(a=>{const target=a.hash.slice(1),active=target==='/'?path==='/':path===target||path.startsWith(target+'/');a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 const work=path==='/'?engagementHome():path==='/engage'?explorePage(params):path==='/profile'?profilePage():path==='/assistant'?assistantPage():path==='/people'?peoplePage(params):path.startsWith('/people/')?personPage(path.split('/')[2]):path==='/build-challenges/new'?Promise.resolve(challengeForm()):path==='/build-challenges'?challengesPage():path.startsWith('/entries/')?entryDetail(path.split('/')[2]):challengeDetail(path.split('/')[2]);
 work.then(html=>{if(sequence!==engagementSequence)return;main.innerHTML=html;document.title=(main.querySelector('h1')?.textContent||'Marketplace')+' | UB AI Innovation Marketplace';bindEngagement();if(focus){window.scrollTo(0,0);main.focus();}}).catch(error=>{if(sequence===engagementSequence)main.innerHTML=heading('Marketplace','Unable to Load This Page')+`<div class="wrap section">${note(error.message,true)}<button class="button" id="retry-engagement">Try Again</button></div>`;document.querySelector('#retry-engagement')?.addEventListener('click',()=>render(false));});
};
for(const kind of ['opportunities','projects','communities']){
 const base=kind==='opportunities'?oppCard:kind==='projects'?projectCard:groupCard;
 const wrapped=r=>base(r).replace('<a class="card-bottom"',`<div class="card-engagement"><span>♡ ${r.likes||0} ${(r.likes||0)===1?'like':'likes'}</span><a href="#/${kind}/${r.id}">${r.comments||0} ${(r.comments||0)===1?'comment':'comments'}</a></div><a class="card-bottom"`);
 if(kind==='opportunities')oppCard=wrapped;else if(kind==='projects')projectCard=wrapped;else groupCard=wrapped;
}
